---
# sabnzbd.persistentvolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/sabnzbd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
---
# sabnzbd.persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: sabnzbd
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---