---
# sonarr.persistentvolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/sonarr-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
---
# sonarr.persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: sonarr-config
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---