kind: Service
apiVersion: v1
metadata:
  name: transmission
  namespace: media
spec:
  selector:
    app: transmission
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
  sessionAffinity: None