kind: Service
apiVersion: v1
metadata:
  name: transmission
  namespace: media
spec:
  selector:
    app: transmission
  ports:
  - name: http
    port: 9091
    protocol: TCP
  - name: torrent-tcp
    port: 51413
    protocol: TCP
  - name: torrent-udp
    port: 51413
    protocol: UDP
