apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: skynamo
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: MSSQL_PID
          value: Developer
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/data
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data

---
kind: Service
apiVersion: v1
metadata:
  name: mssql
  namespace: skynamo
spec:
  selector:
    app: mssql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433

---
kind: Ingress
apiVersion: networking.k8s.io/v1 
metadata:
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
  #   nginx.ingress.kubernetes.io/proxy-read-timeout: "15"      
  name: mssql
  namespace: skynamo
spec:
  rules:
    - host: mssql.steenkamps.org
      http:
        paths:
          - pathType: Prefix
            path: /              
            backend:
              service:
                name: mssql
                port: 
                  number: 1433

---
# mssql.persistentvolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/mssql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - app
  
---
# mssql.persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: skynamo
  name: mssql-data
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
