apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  namespace: media
spec:
  selector:
    matchLabels:
      app: library
  replicas: 1
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library
        image: linuxserver/lazylibrarian:latest
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "816"
        - name: PGID
          value: "816"
        - name: TZ
          value: "Africa/Johannesburg"
        ports:
        - containerPort: 5299
        volumeMounts:
        - name: config
          mountPath: /config
        - name: complete
          mountPath: /downloads
        - name: books
          mountPath: /books
      volumes:
      - name: config
        nfs: 
          server: 192.168.1.100
          path: /mnt/VOL1/sabnzbd/books_config
      - name: complete
        nfs: 
          server: 192.168.1.100
          path: /mnt/VOL1/sabnzbd/complete
      - name: books
        nfs: 
          server: 192.168.1.100
          path: /mnt/VOL1/sabnzbd/books              