apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: transmission-config
            optional: false
        - secretRef:
            name: vpn-creds
            optional: false
        image: haugene/transmission-openvpn
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 9091
          timeoutSeconds: 2
        name: transmission
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          tcpSocket:
            port: 9091
          timeoutSeconds: 2
        resources:
          limits:
            memory: 2000Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /data
        - name: complete
          mountPath: /complete
        - name: watch-folder
          mountPath: /watch
        - name: tunnel
          mountPath: /dev/net/tun
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: transmission-config
      - name: complete
        persistentVolumeClaim:
          claimName: sabnzbd-complete
      - name: watch-folder
        persistentVolumeClaim:
          claimName: watch-folder
      - hostPath:
          path: /dev/net/tun
          type: ""
        name: tunnel
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime