apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
spec:
  selector:
    matchLabels:
      app: sabnzbd
  replicas: 1
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "816"
        - name: PGID
          value: "816"
        - name: TZ
          value: "Africa/Johannesburg"
        - name: VERSION
          value: "latest"
        - name: UMASK_SET
          value: "022"
        - name: PLEX_CLAIM
          value: "claim-R-vi57Dcwx8aPxBBYMg8"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /config
        - name: complete
          mountPath: complete
        # - name: incomplete
        #   mountPath: sabnzbd/incomplete
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd    
      - name: complete
        persistentVolumeClaim:
          claimName: sabnzbd-complete

      # - name: config
      #   nfs: 
      #     server: 192.168.1.100
      #     path: /mnt/VOL1/sabnzbd/sabnzbd_config
      # - name: complete
      #   nfs: 
      #     server: 192.168.1.100
      #     path: /mnt/VOL1/sabnzbd/complete
      # - name: incomplete
      #   nfs: 
      #     server: 192.168.1.100
      #     path: /mnt/VOL1/sabnzbd/incomplete                    