apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "816"
        - name: PGID
          value: "816"
        - name: TZ
          value: "Africa/Johannesburg"
        - name: VERSION
          value: "latest"
        - name: UMASK_SET
          value: "022"

        ports:
          - name: pms
            containerPort: 7878

        volumeMounts:
        - name: config
          mountPath: /config
        - name: complete
          mountPath: /complete
        - name: tv
          mountPath: /tv
        - name: movies
          mountPath: /movies
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: complete
        persistentVolumeClaim:
          claimName: sabnzbd-complete
      - name: tv
        nfs:
          server: 192.168.1.100
          path: /mnt/VOL1/tv
      - name: movies
        nfs:
          server: 192.168.1.100
          path: /mnt/VOL1/movies
