apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media
spec:
  selector:
    matchLabels:
      app: transmission
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "816"
        - name: PGID
          value: "816"
        - name: TZ
          value: "Africa/Johannesburg"
        - name: USER
          value: "lino"
        - name: PASS
          value: "3klop3"

        ports:
          - name: http
            containerPort: 9091
            protocol: TCP
          - name: torrent-tcp
            containerPort: 51413
            protocol: TCP
          - name: torrent-udp
            containerPort: 51413
            protocol: UDP

        volumeMounts:
        - name: config
          mountPath: /config
        - name: complete
          mountPath: /complete
        - name: watch-folder
          mountPath: /watch
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: transmission-config
      - name: complete
        persistentVolumeClaim:
          claimName: sabnzbd-complete
      - name: watch-folder
        persistentVolumeClaim:
          claimName: watch-folder
